# Generated by Django 4.1.3 on 2024-10-23 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Öğrenci ID')),
                ('student_namesurname', models.CharField(max_length=200, verbose_name='Öğrenci Ad Soyad')),
                ('student_birthday', models.DateField(verbose_name='Öğrenci Doğum Tarihi')),
                ('student_school', models.CharField(max_length=255, verbose_name='Öğrenci Okulu')),
                ('student_email', models.EmailField(max_length=254, verbose_name='Öğrenci Email')),
                ('password', models.CharField(max_length=128, verbose_name='Öğrenci Şifresi')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Öğrenci',
                'verbose_name_plural': 'Öğrenciler',
            },
        ),
    ]
