# Generated by Django 5.1.2 on 2024-10-31 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('question_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Soru ID')),
                ('image', models.ImageField(upload_to='questions/', verbose_name='Soru Fotoğrafı')),
                ('gemini_response', models.TextField(verbose_name='Gemini Cevabı')),
                ('created_time', models.DateField(auto_now_add=True, verbose_name='Tarih')),
                ('student_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='dashboard.students', verbose_name='Öğrenci Bilgisi')),
            ],
        ),
    ]
