# Generated by Django 5.1.2 on 2024-11-02 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_questions_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MermaidHistory',
            fields=[
                ('history_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Mermaid Geçmiş ID')),
                ('prompt_text', models.TextField(verbose_name='Mermaid Prompt')),
                ('generated_code', models.TextField(verbose_name='Mermaid Kodu')),
                ('created_time', models.DateField(auto_now_add=True, verbose_name='Tarih')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mermaid_history', to='dashboard.students', verbose_name='Öğrenci Bilgisi')),
            ],
        ),
    ]
